AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-glue

  Sample SAM Template for sam-glue
Parameters:
 EnvBucket:
   Type: String
Resources:
  PaymentsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: payments
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '3.0'
      MaxCapacity: 5
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: glue_job_source/data_cleaning_and_lambda.py
      Role: !GetAtt GlueServiceRole.Arn

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  GlueRoleAllowCrawlingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub "${EnvBucket}"
              - !Sub "${EnvBucket}/*"
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::awsglue-datasets/examples/medicare/*
        Version: '2012-10-17'
      PolicyName: GlueRoleAllowCrawlingPolicy
      Roles:
        - !Ref 'GlueServiceRole'
  MedicareCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: !GetAtt 'GlueServiceRole.Arn'
      Targets:
        S3Targets:
          - Path: s3://awsglue-datasets/examples/medicare/
      DatabaseName: !Ref 'PaymentsDatabase'
      Name: crawler_medicare

Outputs:
  awsConfigUPDATE:
    Value: !Join
      - ''
      - - glue_role_arn=
        - !GetAtt 'GlueServiceRole.Arn'


